# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'AgoraMultiChannelSwitch' do
  # Agora sdk 4.0.0 preview
#  pod 'AgoraRtcEngine_iOS_Preview', '4.0.0.preview.6'
  pod 'AgoraRtcEngine_iOS', '~> 4.1.0'
  pod 'AGEVideoLayout', '~> 1.0.2'
  
  # RTM 1.6.0
  pod 'AgoraRtm_Special_iOS', '1.6.0.202'
  
  # Progress
  pod 'MBProgressHUD'
  
  # PromiseKit
  pod 'PromiseKit'
  pod 'PromiseKit/Alamofire'

  # DarkEggKit
  pod 'DarkEggKit'
  pod 'DZAnimatedGift'
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
    # Check out: https://github.com/flutter/flutter/issues/123852
    # Workaround for Xcode 14.3:
    system('sed -i \'\' \'44s/readlink/readlink -f/\' \'Pods/Target Support Files/Pods-Runner/Pods-Runner-frameworks.sh\'')
end
